In [1]:
from GauAPIs.Molecule import Molecule
from GauAPIs import New_Calculator
from sys import argv
import numpy as np
import os


In [12]:
#define a temperate way to quickly test the feasibility of xtb API
filein = ''
fileout = 'test_res.out'

def get_external_coord(filein):
    with open(filein, 'r') as f:
        [atoms, deriva, charge ,spin] = [int(s) for s in f.readline().split()]
        ele = np.zeros((atoms,), dtype = int)
        
        atomlist = np.zeros((atoms,3), dtype = float)

        for i in range(atoms):
            axestr = f.readline().split()
            ele[i] = int(axestr[0])
            atomlist[i][0] = float(axestr[1])*0.52917724
            atomlist[i][1] = float(axestr[2])*0.52917724
            atomlist[i][2] = float(axestr[3])*0.52917724
    return ele, atomlist, deriva, charge, spin




In [6]:

#print(ele, atomlist, deriva, charge, spin)
import numpy as np
elelist, coors, deriva, charge, spin = get_external_coord(filein)
print(deriva, charge, spin)
Mole = Molecule(elelist,coors,charge,spin,'testorc')
#Ene, Gradient = New_Calculator.calculate_mol_xTB(Mole,1)
#print(Ene)
#print(Gradient)


0 -1 1


In [3]:
try:
    from xtb.libxtb import VERBOSITY_FULL, VERBOSITY_MINIMAL, VERBOSITY_MUTED
    from xtb.interface import Environment, Calculator, Param
except ImportError:
    print('no xTB module found.')
env = Environment()
env.set_output("env_error.log")
env.set_verbosity(VERBOSITY_FULL)
if env.check != 0:
    env.show("Error message")
env.release_output()

os.system('export OMP_NUM_THREADS=4')
os.system('export MKL_NUM_THREADS=4')

########################################################################
[ERROR] Error message
-1- xtb_api_setOutput: File already opened in another unit
########################################################################


0

In [9]:
def calculate_mol_xTB(mol,xtbpara):
    #first solve the environment
    try:
        from xtb.libxtb import VERBOSITY_FULL, VERBOSITY_MINIMAL
        from xtb.interface import Environment, Calculator, Param
    except ImportError:
        print('no xTB module found.')
    
    env = Environment()
    env.set_output("env_error.log")
    env.set_verbosity(VERBOSITY_FULL)
    if env.check != 0:
        env.show("Error message")
    env.release_output()

    xtbpara = Param(xtbpara)
    #define structure data for molecule
    eles_nums = mol.elements
    coors = mol.coordinates
    coors = np.divide(coors,0.52917724)
    #define calculator based on input xtbpara and mol
    calc = Calculator(xtbpara,eles_nums,coors)
    calc.set_verbosity(VERBOSITY_MINIMAL)
    #Calculation
    res = calc.singlepoint()
    Ene = res.get_energy()
    Grad = res.get_gradient()
    print(Ene,Grad)
    return Ene, Grad

In [11]:
calculate_mol_xTB(Mole,1)

########################################################################
[ERROR] Error message
-1- xtb_api_setOutput: File already opened in another unit
########################################################################
   1   -138.7713381 -0.138771E+03  0.462E+00    1.60       0.0  T
   2   -137.8395819  0.931756E+00  0.342E+00    0.16       1.0  T
   3   -137.8916097 -0.520278E-01  0.302E+00    0.38       1.0  T
   4   -139.0136611 -0.112205E+01  0.198E+00    1.45       1.0  T
   5   -139.0214873 -0.782624E-02  0.155E+00    0.67       1.0  T
   6   -139.0169808  0.450655E-02  0.164E+00    1.47       1.0  T
   7   -139.2208390 -0.203858E+00  0.906E-01    1.71       1.0  T
   8   -139.2276479 -0.680894E-02  0.706E-01    1.64       1.0  T
   9   -139.1704221  0.572258E-01  0.822E-01    1.68       1.0  T
  10   -139.1199665  0.504557E-01  0.116E+00    1.47       1.0  T
  11   -139.2092791 -0.893126E-01  0.537E-01    1.54       1.0  T
  12   -139.2343144 -0.250353E-01  0.377E-01   

(-137.8298047069819,
 array([[ 3.04256025e-02, -3.39294368e-02, -3.23518383e-02],
        [-3.21324258e-02,  3.52768498e-02,  3.88391037e-02],
        [ 7.57239367e-03, -1.16840015e-04, -1.30046639e-02],
        [-1.49604141e-02,  6.87909345e-03,  3.90299075e-02],
        [ 1.03432076e-02, -3.16272320e-03, -8.58327642e-03],
        [-6.69554336e-03,  1.53031115e-03,  4.79343559e-03],
        [ 1.86184390e-03,  3.65559922e-03, -3.30813120e-03],
        [ 5.12407389e-03,  5.55138727e-04, -2.31582683e-03],
        [-3.00497044e-03,  1.31214821e-03, -2.20424295e-03],
        [-1.13863759e-03, -2.36955564e-03, -6.93166806e-04],
        [ 8.32408714e-04,  5.20976067e-04, -5.45652531e-04],
        [ 4.61419102e-03,  3.90436879e-04,  1.10155695e-03],
        [-1.96508736e-03, -1.45619462e-03,  5.42398756e-03],
        [ 1.60392632e-03, -3.92635771e-03, -2.01383793e-03],
        [-3.96283586e-03, -1.12252044e-03,  4.03908380e-03],
        [-2.38651873e-03,  2.44044254e-03, -1.49022520e-03],
   

In [ ]:

mol = Mole
#define structure data for molecule
eles_nums = mol.elements
coors = mol.coordinates
#print(eles_nums)
#print(coors)
#define calculator based on input xtbpara and mol

calc = Calculator(Param.GFN2xTB, eles_nums, coors)
calc.set_verbosity(VERBOSITY_MINIMAL)
calc.set_verbosity(VERBOSITY_MUTED) 
res = calc.singlepoint()
res.get_gradient()
#res.get_bond_orders()


In [ ]:
numbers = np.array([8, 1, 1])
positions = np.array([
[ 0.00000000000000, 0.00000000000000,-0.73578586109551],
[ 1.44183152868459, 0.00000000000000, 0.36789293054775],
[-1.44183152868459, 0.00000000000000, 0.36789293054775]])

print(numbers)
print(positions)
calc = Calculator(Param.GFN2xTB, numbers, positions)
calc.set_verbosity(VERBOSITY_MINIMAL)
res = calc.singlepoint()
print(res.get_gradient())
print('*'*10)
res.get_bond_orders()

In [ ]:

global eleslist
eleslist = ['H','He',
        'Li','Be','B','C','N','O','F','Ne',
        'Na','Mg','Al','Si','P','S','Cl','Ar',
        'K','Ca','Sc','Ti','V','Cr','Mn','Fe','Co','Ni','Cu','Zn','Ga','Ge','As','Se','Br','Kr']



In [ ]:
#mol2xyz(Mole)

nums = Mole.get_num_atoms()
print(Mole.elements)
fw = open('/share/home/Liaoyt/APIs/test.xyz','w')
fw.write('%d\n\n'%(nums))
for i in range(nums):
    print('1')
    fw.write('%s %f %f %f\n'%(eleslist[Mole.elements[i]-1],Mole.coordinates[i][0],Mole.coordinates[i][1],Mole.coordinates[i][2]))
fw.write('\n')
fw.close()        

In [ ]:
#ANI 

try:
    import torch
    import torchani
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

except ImportError:
    print('no ANI module found')



model = torchani.models.ANI2x(periodic_table_index=True).to(device).double()

In [ ]:

def calculate_mol_ani(mol,methodani):
    if methodani.lower() in ['ani-1x', 'ani-2x','ani-1ccx']:
        if methodani.lower() == 'ani-2x':
            model = torchani.models.ANI2x(periodic_table_index=True).to(device).double()
        elif methodani.lower() == 'ani-1ccx':
            model = torchani.models.ANI1ccx(periodic_table_index=True).to(device).double()
        elif methodani.lower() == 'ani-1x':
            model = torchani.models.ANI1x(periodic_table_index=True).to(device).double()
        else:
            print('Error: Method not recognised, Using ANI2x instead')
            model = torchani.models.ANI2x(periodic_table_index=True).to(device).double()
    
    print(Mole.elements)
    #have to convert from np to tensor 
    coordinates = torch.from_numpy(mol.coordinates).requires_grad_(True).unsqueeze(0)
    species = torch.from_numpy(mol.elements).unsqueeze(0)
    ene = model((species, coordinates)).energies
    derivative = torch.autograd.grad(ene.sum(), coordinates)[0]
    force = -derivative
    #convert tensor to numpy and return
    return ene.item(),derivative.numpy()


In [ ]:
a,b = calculate_mol_ani(Mole,'ani-2x')


In [2]:
#aiqm test
import mlatom as ml
import os

def mol2xyz(mol):
    nums = mol.get_num_atoms()
    print(mol.elements)
    fw = open('/share/home/Liaoyt/APIs/test.xyz','w')
    fw.write('%d\n\n'%(nums))
    for i in range(nums):
        fw.write('%s %f %f %f\n'%(eleslist[mol.elements[i]-1],mol.coordinates[i][0],mol.coordinates[i][1],mol.coordinates[i][2]))
    fw.write('\n')
    fw.close()        


In [3]:

def calculate_mol_mlatom(xyzfile,charge,spin,methodmlatm):
    #read molecule in 
    mol = ml.data.molecule.from_xyz_file(xyzfile)
    mol.charge = charge
    mol.multiplicity = spin
    #define model
    model = ml.models.methods(method=methodmlatm)
    
    #calculate energy and force
    model.predict(molecule=mol)

    ene = mol.energy
    grad = mol.get_energy_gradients()
    return ene,grad


#os.system("export mndobin=/share/apps/MNDO/BIN/mndo")
#os.system('export dftd4bin=/share/home/Liaoyt/app/dftd4-3.5.0/bin/dftd4')


In [1]:
#os.system('source /share/home/Liaoyt/bin/env/aiqm1-env.sh')
import mlatom as ml
xyz = '/share/home/Liaoyt/apiTEst/AIQM1-input.xyz'
mol = ml.data.molecule.from_xyz_file(xyz)
charge=0
spin=1
model = ml.models.methods(method='AIQM1')
model.predict(molecule=mol)



ValueError: Can't find appropriate program for the requested method, please set the environment variable: export mndobin=... or export sparrowbin=...

In [35]:
def Get_orca_grad(outname,mol):
    fg = open(outname,"r")
    lines = fg.readlines()
    fg.close()
    nums = mol.get_num_atoms()
    print(nums)
    grad_arr = np.zeros((nums,3),dtype=float)
    for line in lines:  
        if "CARTESIAN GRADIENT" in line:
            index_of_grad = lines.index(line)
            break
        counts = 0
    for grads in lines[index_of_grad+3:index_of_grad+2+nums]:
        print(counts)
        grad_arr[counts] = np.array([float(grads.split()[3]),float(grads.split()[4]),float(grads.split()[5])])
        print(grad_arr)
        counts += 1
    
    return grad_arr

In [40]:
grad_arr = np.zeros((6,3),dtype=float)
for i in range(len(grad_arr)):
    grad_arr[i] = np.array([1,1,1])
    print(grad_arr)

[[1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [36]:
test_grad = Get_orca_grad('/share/home/Liaoyt/APIs/testorc.log',Mole)

82
0
[[ 2.7000000e-08 -1.0000000e-09 -9.2875463e-02]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 0.0000000e+00  0.0000000e+00  0.

IndexError: list index out of range